/**  Lenguaje
-----------------------------*/
const Language = {
  es: {
    noResults:"No hay resultados de la busqueda.",
    cancel:"Cancelar",
    edit:"Editar",
    author: "Autor",
    category: "Categoria",
    search: "Buscar",
    backToHome: "Volver al Inicio",
    errorInfo:"Lo Sentimos pero el código que buscas no existe, puede ser que se haya borrado.",
    errorSubtitle: "Opps, no ha sido encontrado.",
    beautifulLife: "La vida es bella",
    loadMore: "Cargar mas",
    saveSettings: "Guardar ajustes",
    save: "Guardar",
    labelApiUrl: "Url de la Api",
    labelToken: "Bearer token",
    labelBio: "Bio",
    labelName: "Nombre",
    settingsTitle: "Ajustes de la app",
    settingsSubtitle: "Datos necesarios para la conexión con la base de datos.",
    settingsSuccessSave: "Ajustes guardadtos con exito.",
    delete: "Borrar",
    publicCode: "¿Código publico?",
    whiteCode: "Escribe el Código",
    description: "Descripcción del Código",
    codeName: "Nombre del Código",
    sureDelete: "¿Esta seguro de borrar el código?",
    longTitleOrDescription: "El titulo o la descripcción es demasiado largo.",
    saveCode: "Guardar código",
    selectTheme: "Selecionar tema de color",
    selectLanguage:"Lenguaje",
    selectCategory:"Categoria"
  },
  en: {
    noResults:"There are no search results.",
    cancel:"Cancel",
    edit:"Edit",
    author: "Author",
    category: "Category",
    search: "Search",
    backToHome: "Back to home",
    errorInfo:"We are sorry but the code you are looking for does not exist, it may have been deleted.",
    errorSubtitle: "Opps, it has not been found.",
    beautifulLife: "Life is Beautiful",
    loadMore: "Load More",
    saveSettings: "Save settings",
    save: "Save",
    labelApiUrl: "Api url",
    labelToken: "Bearer token",
    labelBio: "Bio",
    labelName: "Name",
    settingsTitle: "App settings",
    settingsSubtitle: "Necessary data for the connection with the database.",
    settingsSuccessSave: "Settings saved successfully.",
    delete: "Delete",
    publicCode: "Public code?",
    whiteCode: "Write code",
    description: "Snippet description",
    codeName: "Snippet name",
    sureDelete: "Are you sure to delete Snippet?",
    longTitleOrDescription: "Title or description too long",
    saveCode: "Save code",
    selectTheme: "Select theme color",
    selectLanguage:"Language",
    selectCategory:"Category"
  },
};

export default Language;
